export {default as Header} from './header/Header'
export {default as Footer} from './footer/Footer'
export {default as AboutUs} from './About-Us/About_Us'
export {default as ContactUs} from './pages/Contact-Us/ContactUs'
export {default as FAQ} from './pages/FAQ/FAQ'
export {default as Carousel} from './Carousel/Carousel'
export {default as Breadcrumbs} from './breadcrumbs/Breadcrumbs'
export {default as Cards} from './cards/Cards'
export {default as AsideMenu} from './aside-menu/AsideMenu'
export {default as Home} from './pages/Home/Home'
export {default as Availability} from './availability/Availability'

